# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dev Blog - Team POPONG
description: > # this means to ignore newlines until "baseurl:"
    팀포퐁은 기술을 바탕으로 정치를 보다 쉽고 재미있게 하기 위한 비영리, 무소속의 중립적 단체입니다.
    Team POPONG is a nonprofit, nonpartisan group in Korea that aims to make politics easy and fun via technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.popong.com" # the base hostname & protocol for your site
homepage: "http://popong.com"
twitter_username: teampopong
github_username: teampopong

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
